app/models.py
from app import db
from flask_login import UserMixin
from datetime import datetime
import pytz

india = pytz.timezone('Asia/Kolkata')
now = datetime.now(india)

class User(db.Model, UserMixin):
    id = db.Column(db.Integer, primary_key = True)
    username = db.Column(db.String(150))
    email = db.Column(db.String(150), nullable = False,unique = True)
    password = db.Column(db.String(200), nullable= False)
    
    #one to many , one user manuy notes
    notes = db.relationship('Note', backref = 'author' , lazy= True)
    
    
    def __repr__(self):
        return f"<User {self.username}>"
class Note(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    title = db.Column(db.String(100), nullable=False)
    content = db.Column(db.Text, nullable=False)
    date_created = db.Column(db.DateTime, default = now)
    date_updated = db.Column(db.DateTime, onupdate= now)

    #forien key to User
    user_id = db.Column(db.Integer, db.ForeignKey('user.id'), nullable = False)
    
    def __repr__(self):
        return f"<Note {self.id}>"

from app import login_manager

@login_manager.user_loader
def load_user(user_id):
    return User.query.get(int(user_id))

app/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField, SubmitField,  TextAreaField
from wtforms.validators import DataRequired, Length, Email, EqualTo, ValidationError
from app.models import User

class RegisterForm(FlaskForm):
    username = StringField('Username', validators=[DataRequired(), Length(min=3, max=20)])
    email = StringField('Email', validators=[DataRequired(), Email()]) 
    password = PasswordField('Password', validators=[DataRequired(), Length(min=6)])
    confirm_password = PasswordField('Confirm Password', validators=[DataRequired(), EqualTo('password')])
    
    submit =  SubmitField('Sign Up')
    def validate_email(self, email):
        user = User.query.filter_by(email=email.data).first()
        if user:
            raise ValidationError('Email already registered. Please use a different one.')   

class LoginForm(FlaskForm):
    email = StringField('Email', validators=[DataRequired(), Email()])
    password =  StringField('Password', validators=[DataRequired()])
    submit = SubmitField('Login')
    
class NoteForm(FlaskForm):
    title = StringField('Title', validators=[DataRequired(), Length(min=1, max=100)])
    content = TextAreaField('Your Note', validators=[DataRequired()])
    submit = SubmitField('Add Note')
    

app/__init__.py
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from flask_bcrypt import Bcrypt
from flask_wtf.csrf import CSRFProtect
from flask_login import LoginManager


db = SQLAlchemy()
bcrypt = Bcrypt()
csrf = CSRFProtect()
login_manager = LoginManager()
login_manager.login_view = 'main.login'
login_manager.login_message = "Please log in to access this page."
login_manager.login_message_category = 'info'     # flash category



def create_app():   
    app = Flask(__name__)
    
    app.config["SECRET_KEY"] = 'mysecretkey'
    app.config["SQLALCHEMY_DATABASE_URI"] = 'sqlite:///site.db'
    
    #extensions
    db.init_app(app)
    bcrypt.init_app(app)
    login_manager.init_app(app)
    
    #blueprint for routes
    from app.routes import main
    app.register_blueprint(main)
    
    # 🔁 Later: Register blueprints here (e.g., auth, notes, etc.)
    
    return app

app/routes.py
from flask import Flask, Blueprint, render_template, url_for, flash, redirect, request
from sqlalchemy import case, desc
from app.forms import RegisterForm, LoginForm, NoteForm
from app.models import User, Note, now
from app import db, bcrypt
from flask_login import  login_user, login_required, current_user, logout_user
from datetime import datetime
import pytz
#
india = pytz.timezone('Asia/Kolkata')
now = datetime.now(india)

#START HERE
main = Blueprint('main', __name__)

@main.app_errorhandler(401)
def unauthorized_error(error):
    return render_template('login.html'), 401

@main.route("/")
def home():
    return redirect(url_for('main.login'))

@main.route("/register", methods=['GET', 'POST'])
def register():
    form = RegisterForm()
    if form.validate_on_submit():
        hashed_pw = bcrypt.generate_password_hash(form.password.data).decode('UTF-8')
        
        new_user = User(username = form.username.data, email = form.email.data, password = hashed_pw )
        db.session.add(new_user)
        db.session.commit()
        
        flash(f'Account created for {form.username.data}!', 'success')
        
        return redirect(url_for('main.login'))
    return render_template('register.html', form= form)


@main.route('/login', methods=['POST', 'GET'])
def login():
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email = form.email.data).first()
        if user and bcrypt.check_password_hash(user.password, form.password.data):
            login_user(user)
            flash('Login successful!', 'success')
            next_page=request.args.get('next')
            return redirect(next_page) if next_page else redirect(url_for('main.dashboard'))
        else:
            flash('Login Filed, Please check email and password', 'danger')
    return render_template('login.html', form = form)


@main.route('/dashboard', methods=['POST', 'GET'])
@login_required
def dashboard():
    form = NoteForm()
    
    if form.validate_on_submit():
        new_note = Note(title = form.title.data, content = form.content.data, author = current_user)
        db.session.add(new_note)
        db.session.commit()
        flash("Note added successfully", 'success')
        return redirect(url_for('main.dashboard'))
    
    base_query = Note.query.filter_by(user_id=current_user.id)
    
    #search logic here
    search_term = request.args.get("q", "").strip()
    
    if search_term:
        base_query= base_query.filter((Note.title.ilike(f"%{search_term}%")) | Note.content.ilike(f"%{search_term}%"))
    
    #sorting logic for note added OR note_updated    
    notes = base_query.order_by(desc(
        case(
            (Note.date_updated != None, Note.date_updated), else_= Note.date_created
            )
        )).all()
        
    return render_template('dashboard.html', form = form, notes = notes)

@main.route('/delete/<int:note_id>', methods = ['POST'])
@login_required
def delete_note(note_id):
    note = Note.query.get_or_404(note_id)
    
    if note.author !=  current_user:
        flash("You don't have permission to delet", "danger")
        return redirect(url_for('main.dashboard'))
    
    db.session.delete(note)
    db.session.commit()
    flash('Note deleted successfully', 'danger')
    return redirect(url_for('main.dashboard'))

@main.route('/edit/<int:note_id>', methods=['POST', 'GET'])
@login_required
def edit_note(note_id):
    note = Note.query.get_or_404(note_id)
    print(note)
    
    if note.author != current_user:
        flash("You are not authorized to edit,", "danger")
        return redirect(url_for('main.dashboard'))
    
    form = NoteForm()
    
    if request.method=='GET':
        form.title.data = note.title
        form.content.data = note.content
        

    if form.validate_on_submit():
        note.title = form.title.data
        note.content = form.content.data
        note.date_updated = now
        db.session.commit()
        flash("Note update sucessfully", 'success')
        return redirect(url_for('main.dashboard'))

    return render_template('edit_note.html', form=form, note = note)

    
@main.route('/profile', methods=['POST', 'GET'])
@login_required
def profile():
    return render_template('profile.html', user = current_user)



@main.route('/logout')
@login_required
def logout():
    logout_user()
    flash("You've been logged out.", "info")
    return redirect(url_for('main.login'))

app/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Flask Notes App</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='css/style.css') }}">
</head>
<body>
    <header> 
        <nav>
            <a href="{{ url_for('main.dashboard') }}">Dashboard</a>
            <a href="{{ url_for('main.profile') }}">Profile</a>
            <a href="{{ url_for('main.logout') }}">Logout</a>
        </nav>
    </header>

    <div class="container">
        {% with messages = get_flashed_messages(with_categories=true) %}
            {% if messages %}
                <ul class="flashes">
                {% for category, message in messages %}
                    <li class="flash-message {{ category }}">{{ message }}</li>
                {% endfor %}
                </ul>
            {% endif %}
        {% endwith %}

        {% block content %}
        {% endblock %}

        
    </div>
    
    <footer>
        <p>&copy;2025 My flask Notes App</p>
    </footer>
   
    <script>
        setTimeout(() => {
          const alerts = document.querySelectorAll('.flashes');
          alerts.forEach(alert => alert.style.display = 'none');
        }, 5000); // hide after 3 seconds
      </script>
      
</body>
</html>

app/templates/dashboard.html
{% extends 'base.html' %}

{% block title %}Dashboard{% endblock%}

{% block content %}

<h1 class="page-title">Welcome to dashboard {{current_user.username}} </h1> 
<nav>
    <a href="{{ url_for('main.profile') }}">View Profile</a>  
</nav>
    <div class="logout-wrapper">
        <a href="{{ url_for('main.logout') }}" class="logout">Logout</a>
    </div>


<div class="search-add-container">
    <!--we have added a form for searching the required notes-->
    <form method="GET" action="{{ url_for('main.dashboard') }}" class="search-form">
        <input type="text" name="q" placeholder="Search your notes here..." value="{{ request.args.get('q', '') }}" required>
        <!--if block for clear the search place, as if search_item is there shows clear buttor, if not not shows  -->
        {% if request.args.get('q') %}
            <a href="{{ url_for('main.dashboard') }}" class="clear-search">Clear</a>
        {% else %}
            <button type="submit">Search</button>
        {% endif %}
    </form>
    <div>
    <!--adding note(form submit) here, submit button-->
    <button id="addNoteBtn" class="note-btn add-note-btn">+ Add Note</button>
    </div>
    <div id="newNoteForm" class="hidden-form">
        <form method="POST" action="{{ url_for('main.dashboard') }}">
            {{ form.hidden_tag() }}
            <div>
                {{ form.title.label }}
                {{ form.title(size=40, class_='input-field') }}<br>

                {{ form.content.label }}<br>
                {{ form.content(rows=3, cols=50, class_='input-field') }}
            </div>

            <div>
                {{ form.submit(class_='note-btn submit-btn', value='Save Note') }}
            </div>
        </form>
    </div>
</div>


<!-- retriving the added notes, and make them alingn in lists-->
{% if notes %}
    <ul class="notes-list">
        {% for note in notes %}
            <li class="note-card">
                <div class="note-meta">
                    <strong class="note_date">
                        {% if note.date_updated and note.date_updated != note.date_created %}
                            Updated_on: {{ note.date_updated.strftime('%b %d, %Y %I:%M %p') }}
                        {% else %}
                            Created_on: {{ note.date_created.strftime('%b %d, %Y %I:%M %p') }}
                        {% endif %}
                    </strong>
                        <form action="{{ url_for('main.delete_note', note_id = note.id) }}" method="POST" style="display: inline;">
                            <button type="submit" class="note-del">Delete</button>
                        </form>
                        <a href="{{ url_for('main.edit_note', note_id=note.id) }} " class="note-edit">Edit</a>
                </div>
                <div class="note-title">Title: {{ note.title }}</div>
                
                <div class="note-content">{{ note.content }}</div>
    
            </li>
        {% endfor %}
    </ul>
{% else %}
    <p>No notes yet. Start adding!, Click on +Add Note</p>
{% endif %}






<script>
    const addNoteBtn = document.getElementById("addNoteBtn")
    const newNoteForm = document.getElementById("newNoteForm")

    addNoteBtn.addEventListener('click', () => {
        if(newNoteForm.style.display == 'none' || newNoteForm.style.display === "") {
            newNoteForm.style.display = "block"
            addNoteBtn.textContent = "Hide Note Form";
        }else{
            newNoteForm.style.display = "none";
            addNoteBtn.textContent = "Add New Note";
        }
    })
</script>

{% endblock %}

app/templates/edit_note.html
{% extends 'base.html' %} 

{% block title %}Login{% endblock %} 

{% block content%}

<h1 class="page-title">Edit note here</h1>

<form method="POST" class="edit-note-form">
  {{ form.hidden_tag() }}

  <div>
    {{ form.title.label }}<br />
    {{ form.title(size=40) }} 
  </div>
  <div>
    {{ form.content.label }}<br />
    {{ form.content(rows=4, cols=50) }}
  </div>

  <div>{{ form.submit( value= 'Update Note') }}</div>
</form>

<p><a href="{{ url_for('main.dashboard') }}" class="bottom-link">Back to Dashboard</a></p>

{% endblock %}

app/templates/login.html
<p class="welcome">Welcome to Notes platform, Please <span style="color: #007bff;">Login</span> to access your notes and features. </p> 
{% extends "base.html" %}

{%block title %}Login{% endblock %}


{% block content%}

<h2 class="page-title"><span style="color: #007bff;">Login</span></h2>

<form method="POST" class="login-tag">
  {{ form.hidden_tag() }}

  <p>
    {{ form.email.label }}<br />
    {{ form.email(size=32) }}<br />
    {% for error in form.email.errors %}
    <span style="color: red">{{ error }}</span>
    {% endfor %}
  </p>

  <p>
    {{ form.password.label }}<br />
    {{ form.password(size=32, type="password")}}<br />
    {% for error in form.password.errors %}
    <span style="color: red">{{ error }}</span>
    {% endfor %}
  </p>

  <p>{{ form.submit()}}</p>
</form>

<p class="bottom-link">
  Don't have an account? <a href="{{ url_for('main.register')}}">Sign Up</a> here.
</p>

{%endblock %}

app/templates/profile.html
{% extends 'base.html' %}
{% block title %}Profile{% endblock %}
{% block content %}
<div class="profile-container">
    <h1>Your Profile, {{ user.username }}</h1>
    <p><strong>Email:</strong><span>{{ user.email }}</span></p>
    <p><strong>Total Notes</strong><span>{{ user.notes | length }}</span></p>

    <a  href=" {{ url_for('main.dashboard')}} ">Back to dashboard</a>
</div>
{% endblock %}

app/templates/register.html
{% extends 'base.html' %}

{% block title %}Register{% endblock %}

{%block content %}

<h2 class="page-title">Register</h2>


<form method="POST" class="register-form">
  {{ form.hidden_tag() }}

  <p>
    {{ form.username.label }}<br />
    {{ form.username(size=32) }}<br />
    {% for error in form.username.errors %}
    <span style="color: red">[{{ error }}]</span>
    {% endfor %}
  </p>

  <p>
    {{ form.email.label }}<br />
    {{ form.email(size=32)}}<br />
    {% for error in form.email.errors %}
    <span style="color: red">[{{ error }}]</span>
    {% endfor %}
  </p>

  <p>
    {{ form.password.label }}<br />
    {{ form.password(size=32) }}<br />
    {% for error in form.password.errors %}
    <span style="color: red">[{{ error }}]</span>
    {% endfor %}
  </p>

  <p>
    {{ form.confirm_password.label }}<br />
    {{ form.confirm_password(size=32) }}<br />
    {% for error in form.confirm_password.errors %}
    <span style="color: red">[{{ error }}]</span>
    {% endfor %}
  </p>

  <p>{{ form.submit() }}</p>
</form>

<p class="bottom-link">Already have an account? <a href="/login">Login</a> here</p>

{% endblock %}